"""
Question Generator Service

Generates follow-up questions based on detected issues.
When use_llm=True, ALL questions are generated by LLM for contextual,
specific questions with actionable suggested answers.
Falls back to templates from validation_checklist.json when LLM is unavailable.
"""

import json
import logging
import re
from typing import List, Dict, Any, Optional
from dataclasses import dataclass

import httpx

from app.config import Settings, get_settings
from app.services.semantic_analyzer import SemanticIssue, IssueType
from app.services.conflict_detector import ConflictIssue, ConflictType

logger = logging.getLogger(__name__)


@dataclass
class FollowUpQuestion:
    """Represents a follow-up question for stakeholders."""
    question_id: str
    question: str
    context: str
    related_issue_type: str
    severity: str
    affected_elements: List[str]
    suggested_answers: Optional[List[str]] = None

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for JSON serialization."""
        return {
            "question_id": self.question_id,
            "question": self.question,
            "context": self.context,
            "related_issue_type": self.related_issue_type,
            "severity": self.severity,
            "affected_elements": self.affected_elements,
            "suggested_answers": self.suggested_answers
        }


class QuestionGenerator:
    """
    Generates follow-up questions based on detected issues.

    When use_llm=True, generates ALL questions via LLM for contextual,
    specific questions with actionable suggested answers.
    Falls back to template-based generation when LLM fails or is disabled.
    """

    def __init__(self, settings: Optional[Settings] = None):
        self.settings = settings or get_settings()
        self._validation_checklist: Optional[dict] = None
        self._question_counter = 0

    async def _call_ollama(self, prompt: str, system_prompt: Optional[str] = None) -> str:
        """Call Ollama API to generate follow-up questions."""
        url = self.settings.get_ollama_generate_url()
        payload = {
            "model": self.settings.OLLAMA_MODEL,
            "prompt": prompt,
            "stream": False,
            "options": {
                "temperature": 0.4,
                "num_predict": 4096
            }
        }
        if system_prompt:
            payload["system"] = system_prompt

        async with httpx.AsyncClient(timeout=self.settings.OLLAMA_TIMEOUT) as client:
            response = await client.post(url, json=payload)
            response.raise_for_status()
            result = response.json()
            return result.get("response", "")

    def _normalize_question(self, text: str) -> str:
        """Normalize question text for deduplication."""
        return re.sub(r"\s+", " ", text.strip().lower())

    @property
    def validation_checklist(self) -> dict:
        """Lazy load validation checklist."""
        if self._validation_checklist is None:
            self._validation_checklist = self.settings.load_validation_checklist()
        return self._validation_checklist

    def _get_next_question_id(self) -> str:
        """Generate next question ID."""
        self._question_counter += 1
        return f"FUQ-{self._question_counter:03d}"

    def _get_template_for_rule(self, rule_id: str) -> Optional[str]:
        """Get question template for a specific rule."""
        rules = self.validation_checklist.get("validation_rules", {})

        for category in rules.values():
            if isinstance(category, dict) and "rules" in category:
                for rule in category["rules"]:
                    if rule.get("id") == rule_id:
                        return rule.get("question_template")

        return None

    # ─── LLM-first question generation ───────────────────────────────

    def _build_issues_data(
        self,
        semantic_issues: List[SemanticIssue],
        conflict_issues: List[ConflictIssue],
    ) -> List[Dict[str, Any]]:
        """Convert all issues into a compact list for LLM prompting."""
        issues = []
        for issue in semantic_issues:
            issues.append({
                "type": issue.issue_type.value,
                "severity": issue.severity,
                "description": issue.description,
                "affected_elements": issue.affected_elements,
                "contexts": issue.contexts,
                "recommendation": issue.recommendation,
            })
        for issue in conflict_issues:
            issues.append({
                "type": issue.conflict_type.value,
                "severity": issue.severity,
                "description": issue.description,
                "affected_elements": issue.affected_elements,
                "contexts": issue.contexts,
                "evidence": issue.evidence,
                "recommendation": issue.recommendation,
            })
        # Sort by severity so LLM focuses on critical issues first
        sev_order = {"HIGH": 0, "MEDIUM": 1, "LOW": 2}
        issues.sort(key=lambda x: sev_order.get(x.get("severity", "MEDIUM"), 3))
        return issues

    async def _generate_all_questions_llm(
        self,
        semantic_issues: List[SemanticIssue],
        conflict_issues: List[ConflictIssue],
        max_questions: int,
    ) -> List[FollowUpQuestion]:
        """
        Generate ALL questions via a single LLM call.

        The LLM receives all detected issues and produces specific,
        contextual questions with actionable suggested answers.
        """
        issues_data = self._build_issues_data(semantic_issues, conflict_issues)
        if not issues_data:
            return []

        system_prompt = (
            "Sei un esperto di Domain-Driven Design. Genera domande di follow-up "
            "per risolvere problemi in un domain model.\n\n"
            "REGOLE:\n"
            "1. Scrivi in ITALIANO\n"
            "2. Ogni domanda DEVE menzionare i nomi reali (entità, domini, eventi)\n"
            "3. Ogni domanda DEVE avere esattamente 3 suggested_answers\n"
            "4. Le suggested_answers DEVONO essere AZIONI SPECIFICHE con nomi reali.\n"
            "   BUONO: 'Assegnare ownership di Product a CatalogContext e usare ProductRef in OrderContext'\n"
            "   BUONO: 'Rinominare OrderCreated in CatalogOrderCreated per il dominio Catalog'\n"
            "   CATTIVO: 'Risolvere il conflitto' (troppo generico!)\n"
            "   CATTIVO: 'Eliminare il duplicato' (non dice come!)\n"
            "5. Se due problemi riguardano lo stesso elemento, RAGGRUPPA in una sola domanda\n"
            "6. Rispondi SOLO con un array JSON valido, NIENTE altro testo\n\n"
            "Schema:\n"
            '[{"question":"...","context":"...","related_issue_type":"ENTITY_OVERLAP|'
            'SEMANTIC_AMBIGUITY|REQUIREMENT_CONFLICT|DUPLICATE_EVENT|NAMING_VIOLATION|'
            'INCOMPATIBLE_PATTERN|MISCLASSIFIED_DOMAIN","severity":"HIGH|MEDIUM|LOW",'
            '"affected_elements":["..."],"suggested_answers":["azione 1","azione 2","azione 3"]}]'
        )

        prompt = (
            f"Analizza questi {len(issues_data)} problemi e genera "
            f"fino a {max_questions} domande di follow-up.\n\n"
            f"Problemi trovati:\n"
            f"{json.dumps(issues_data, indent=2, ensure_ascii=False)}\n\n"
            f"Genera una domanda per ogni problema (o raggruppa problemi correlati).\n"
            f"Rispondi SOLO con un array JSON."
        )

        try:
            response = await self._call_ollama(prompt, system_prompt)
            raw = response.strip()

            # Strip markdown fences if present
            if raw.startswith("```"):
                raw = re.sub(r"```(?:json)?\n?", "", raw).strip()
                raw = raw.strip("`").strip()

            # Extract JSON array from response
            start = raw.find("[")
            end = raw.rfind("]")
            if start >= 0 and end > start:
                raw = raw[start : end + 1]

            parsed = json.loads(raw)
        except Exception as e:
            logger.warning(f"LLM question generation failed: {e}")
            return []

        questions: List[FollowUpQuestion] = []
        if isinstance(parsed, list):
            for item in parsed[:max_questions]:
                if not isinstance(item, dict) or "question" not in item:
                    continue
                # Validate suggested_answers
                sa = item.get("suggested_answers")
                if isinstance(sa, list):
                    sa = [str(a).strip() for a in sa if a]
                    if len(sa) < 2:
                        sa = None
                else:
                    sa = None

                # Clean question text: remove metadata prefixes like [ENTITY_OVERLAP|HIGH]
                q_text = str(item["question"]).strip()
                q_text = re.sub(r"^\[.*?\]\s*", "", q_text).strip()
                # Remove leading newlines
                q_text = q_text.lstrip("\n")

                questions.append(FollowUpQuestion(
                    question_id=self._get_next_question_id(),
                    question=q_text,
                    context=str(item.get("context", "General")),
                    related_issue_type=str(item.get("related_issue_type", "UNKNOWN")),
                    severity=str(item.get("severity", "MEDIUM")),
                    affected_elements=list(item.get("affected_elements", []) or []),
                    suggested_answers=sa,
                ))

        logger.info(f"LLM generated {len(questions)} contextual questions")
        return questions

    # ─── Template-based fallback ─────────────────────────────────────

    def generate_from_semantic_issue(
        self,
        issue: SemanticIssue
    ) -> FollowUpQuestion:
        """Generate a follow-up question from a semantic issue (template fallback)."""
        template = None
        if issue.rule_id:
            template = self._get_template_for_rule(issue.rule_id)

        if issue.issue_type == IssueType.ENTITY_OVERLAP:
            if template:
                try:
                    question = template.format(
                        entity_name=issue.affected_elements[0] if issue.affected_elements else "entity",
                        context_1=issue.contexts[0] if issue.contexts else "context1",
                        context_2=issue.contexts[1] if len(issue.contexts) > 1 else "context2"
                    )
                except KeyError:
                    template = None

            if not template:
                entities = ", ".join(issue.affected_elements[:2])
                contexts = " e ".join(issue.contexts)
                question = (
                    f"L'entità '{entities}' appare in più bounded context "
                    f"({contexts}). Come deve essere gestita?"
                )

            suggested = [
                f"Stessa entità con ownership condivisa tra {' e '.join(issue.contexts)}",
                f"Rappresentazioni diverse con mapping esplicito tra i contesti",
                f"Consolidare in un unico bounded context"
            ]

        elif issue.issue_type == IssueType.SEMANTIC_AMBIGUITY:
            if template:
                try:
                    question = template.format(
                        term=issue.affected_elements[0] if issue.affected_elements else "term",
                        context_name=issue.contexts[0] if issue.contexts else "context"
                    )
                except KeyError:
                    template = None

            if not template:
                term = issue.affected_elements[0].split(":")[0] if issue.affected_elements else "termine"
                question = (
                    f"Il termine '{term}' ha definizioni ambigue o inconsistenti. "
                    f"Come deve essere definito?"
                )

            suggested = [
                "Definire una singola definizione canonica",
                "Usare nomi diversi per ogni contesto",
                "Rimuovere e sostituire con termini più specifici"
            ]

        else:
            question = f"Chiarimento necessario: {issue.description}"
            suggested = None

        return FollowUpQuestion(
            question_id=self._get_next_question_id(),
            question=question,
            context=issue.contexts[0] if issue.contexts else "General",
            related_issue_type=issue.issue_type.value,
            severity=issue.severity,
            affected_elements=issue.affected_elements,
            suggested_answers=suggested
        )

    def generate_from_conflict_issue(
        self,
        issue: ConflictIssue
    ) -> FollowUpQuestion:
        """Generate a follow-up question from a conflict issue (template fallback)."""
        template = None
        if issue.rule_id:
            template = self._get_template_for_rule(issue.rule_id)

        if issue.conflict_type == ConflictType.REQUIREMENT_CONFLICT:
            reqs = "\n".join(f"  - {el}" for el in issue.affected_elements[:2])
            question = (
                f"C'è un conflitto tra questi requisiti:\n{reqs}\n\n"
                f"Quale deve avere la priorità, o come risolvere il conflitto?"
            )
            suggested = [
                f"Priorità al primo requisito: {issue.affected_elements[0][:60]}",
                f"Priorità al secondo requisito: {issue.affected_elements[1][:60]}" if len(issue.affected_elements) > 1 else "Priorità al secondo requisito",
                "Definire condizioni specifiche per ciascuno",
                "Modificare entrambi per eliminare il conflitto"
            ]

        elif issue.conflict_type == ConflictType.DUPLICATE_EVENT:
            event = issue.affected_elements[0] if issue.affected_elements else "evento"
            emitters = ", ".join(issue.contexts)
            question = (
                f"L'evento '{event}' è emesso da più domini: {emitters}.\n"
                f"Quale dominio deve essere l'unico proprietario?"
            )
            suggested = [f"Ownership a {ctx}" for ctx in issue.contexts]
            suggested.append("Creare eventi separati per ogni dominio")

        elif issue.conflict_type == ConflictType.NAMING_VIOLATION:
            event = issue.affected_elements[0] if issue.affected_elements else "evento"
            question = (
                f"L'evento '{event}' usa il tempo presente/imperativo invece del passato.\n"
                f"Gli eventi di dominio devono descrivere ciò che è successo.\n"
                f"Qual è il nome corretto al passato?"
            )
            # Generate smarter past-tense suggestions
            base = event
            suggestions = []
            if base.endswith("e"):
                suggestions.append(f"{base}d")
            elif base.endswith("y"):
                suggestions.append(f"{base[:-1]}ied")
            else:
                suggestions.append(f"{base}ed")
            suggestions.append(f"{base}Completed")
            suggestions.append(f"{base}Processed")
            suggested = suggestions

        elif issue.conflict_type == ConflictType.INCOMPATIBLE_PATTERN:
            question = (
                f"C'è un'incompatibilità tra pattern di comunicazione:\n"
                f"{issue.description}\n\n"
                f"Come deve essere risolto?"
            )
            suggested = [
                "Aggiungere opzione di comunicazione sincrona",
                "Rilassare il requisito di consistenza a eventuale",
                "Ridisegnare il pattern di integrazione"
            ]

        elif issue.conflict_type == ConflictType.MISCLASSIFIED_DOMAIN:
            domain = issue.affected_elements[0] if issue.affected_elements else "dominio"
            question = (
                f"Il dominio '{domain}' potrebbe essere classificato erroneamente.\n"
                f"{issue.description}\n\n"
                f"Qual è la classificazione corretta?"
            )
            suggested = ["Core Domain", "Supporting Domain", "Generic Domain"]

        else:
            question = f"Chiarimento necessario: {issue.description}"
            suggested = None

        return FollowUpQuestion(
            question_id=self._get_next_question_id(),
            question=question,
            context=issue.contexts[0] if issue.contexts else "General",
            related_issue_type=issue.conflict_type.value,
            severity=issue.severity,
            affected_elements=issue.affected_elements,
            suggested_answers=suggested
        )

    # ─── Main entry point ────────────────────────────────────────────

    async def generate_questions(
        self,
        semantic_issues: List[SemanticIssue],
        conflict_issues: List[ConflictIssue],
        max_questions: Optional[int] = None,
        use_llm: bool = False
    ) -> List[FollowUpQuestion]:
        """
        Generate follow-up questions from all detected issues.

        When use_llm=True, generates ALL questions via LLM for contextual,
        specific answers. Falls back to templates if LLM fails.
        """
        logger.info("Generating follow-up questions...")
        max_q = max_questions or self.settings.MAX_FOLLOW_UP_QUESTIONS

        # ── LLM-first path: generate all questions via LLM ──
        if use_llm:
            llm_questions = await self._generate_all_questions_llm(
                semantic_issues, conflict_issues, max_q
            )
            if llm_questions:
                logger.info(
                    f"Generated {len(llm_questions)} LLM-contextual questions"
                )
                return self.prioritize_questions(llm_questions)
            logger.warning(
                "LLM question generation failed, falling back to templates"
            )

        # ── Template fallback ──
        questions = []
        all_issues = []

        for issue in semantic_issues:
            all_issues.append(("semantic", issue, issue.severity))
        for issue in conflict_issues:
            all_issues.append(("conflict", issue, issue.severity))

        severity_order = {"HIGH": 0, "MEDIUM": 1, "LOW": 2}
        all_issues.sort(key=lambda x: severity_order.get(x[2], 3))

        for issue_type, issue, _ in all_issues[:max_q]:
            if issue_type == "semantic":
                questions.append(self.generate_from_semantic_issue(issue))
            else:
                questions.append(self.generate_from_conflict_issue(issue))

        logger.info(f"Generated {len(questions)} template-based questions")
        return questions

    def prioritize_questions(
        self,
        questions: List[FollowUpQuestion]
    ) -> List[FollowUpQuestion]:
        """Prioritize questions by impact and actionability."""
        severity_order = {"HIGH": 0, "MEDIUM": 1, "LOW": 2}
        return sorted(
            questions,
            key=lambda q: (
                severity_order.get(q.severity, 3),
                -len(q.affected_elements)
            )
        )
