"""
A2A Protocol - Artifact Model

Artifacts represent task outputs. They are the results produced by an agent
after processing a task.

Based on A2A Protocol Specification v0.3
"""

from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field
import uuid

from a2a.models.message import Part


class Artifact(BaseModel):
    """
    Artifacts represent task outputs.
    
    An artifact is a piece of output generated by an agent as a result 
    of processing a task. It can contain multiple parts (text, files, 
    structured data).
    """
    artifact_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        alias="artifactId",
        description="Unique identifier (UUID) for the artifact. Must be unique within a task."
    )
    name: Optional[str] = Field(
        None,
        description="A human readable name for the artifact"
    )
    description: Optional[str] = Field(
        None,
        description="A human readable description of the artifact"
    )
    parts: List[Part] = Field(
        ...,
        min_length=1,
        description="The content of the artifact. Must contain at least one part."
    )
    metadata: Optional[Dict[str, Any]] = Field(
        None,
        description="Optional metadata included with the artifact"
    )
    extensions: Optional[List[str]] = Field(
        None,
        description="The URIs of extensions that are present or contributed to this Artifact"
    )

    class Config:
        populate_by_name = True

    @classmethod
    def from_data(
        cls,
        data: Dict[str, Any],
        name: Optional[str] = None,
        description: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None
    ) -> "Artifact":
        """
        Factory method to create an Artifact from structured data.
        
        Args:
            data: The structured data (JSON object)
            name: Human readable name
            description: Human readable description
            metadata: Optional metadata
        """
        return cls(
            name=name,
            description=description,
            parts=[Part.from_data(data)],
            metadata=metadata
        )

    @classmethod
    def from_text(
        cls,
        text: str,
        name: Optional[str] = None,
        description: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None
    ) -> "Artifact":
        """
        Factory method to create an Artifact from text.
        
        Args:
            text: The text content
            name: Human readable name
            description: Human readable description
            metadata: Optional metadata
        """
        return cls(
            name=name,
            description=description,
            parts=[Part.from_text(text)],
            metadata=metadata
        )

    @classmethod
    def from_parts(
        cls,
        parts: List[Part],
        name: Optional[str] = None,
        description: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None
    ) -> "Artifact":
        """
        Factory method to create an Artifact from multiple parts.
        
        Args:
            parts: List of Part objects
            name: Human readable name
            description: Human readable description
            metadata: Optional metadata
        """
        return cls(
            name=name,
            description=description,
            parts=parts,
            metadata=metadata
        )

    def get_data_content(self) -> List[Dict[str, Any]]:
        """Extract all data content from artifact parts."""
        data_list = []
        for part in self.parts:
            if part.data is not None:
                data_list.append(part.data.data)
        return data_list

    def get_first_data(self) -> Optional[Dict[str, Any]]:
        """Get the first data part content, or None if no data parts."""
        for part in self.parts:
            if part.data is not None:
                return part.data.data
        return None

    def get_text_content(self) -> str:
        """Extract all text content from artifact parts."""
        texts = []
        for part in self.parts:
            if part.text is not None:
                texts.append(part.text)
        return "\n".join(texts)


# ============================================================================
# Agent 2 Specific Artifact Types
# ============================================================================
# These are specialized artifact types for the Consistency & Conflict Analyzer

class ValidationReportArtifact(BaseModel):
    """
    Specialized artifact for validation reports produced by Agent 2.
    Contains the structured validation results.
    """
    artifact_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        alias="artifactId"
    )
    name: str = Field(default="Validation Report")
    description: str = Field(default="DDD model consistency and conflict analysis report")
    
    # Validation results
    validation_status: str = Field(
        ...,
        alias="validationStatus",
        description="Overall status: VALID, NEEDS_REVIEW, INVALID"
    )
    problems: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="List of detected problems"
    )
    summary: Dict[str, Any] = Field(
        default_factory=dict,
        description="Summary statistics of validation"
    )
    
    metadata: Optional[Dict[str, Any]] = Field(None)

    class Config:
        populate_by_name = True

    def to_artifact(self) -> Artifact:
        """Convert to standard A2A Artifact."""
        return Artifact(
            artifact_id=self.artifact_id,
            name=self.name,
            description=self.description,
            parts=[Part.from_data({
                "validationStatus": self.validation_status,
                "problems": self.problems,
                "summary": self.summary
            })],
            metadata=self.metadata
        )


class FollowUpQuestionsArtifact(BaseModel):
    """
    Specialized artifact for follow-up questions generated by Agent 2.
    """
    artifact_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        alias="artifactId"
    )
    name: str = Field(default="Follow-up Questions")
    description: str = Field(default="Clarification questions for business stakeholders")
    
    questions: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="List of follow-up questions"
    )
    
    metadata: Optional[Dict[str, Any]] = Field(None)

    class Config:
        populate_by_name = True

    def to_artifact(self) -> Artifact:
        """Convert to standard A2A Artifact."""
        return Artifact(
            artifact_id=self.artifact_id,
            name=self.name,
            description=self.description,
            parts=[Part.from_data({
                "questions": self.questions
            })],
            metadata=self.metadata
        )


class RefinedModelArtifact(BaseModel):
    """
    Specialized artifact for the refined domain model produced by Agent 2.
    This is the main output that goes to Agent 3.
    """
    artifact_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        alias="artifactId"
    )
    name: str = Field(default="Refined Domain Model")
    description: str = Field(default="Validated and corrected domain model ready for Agent 3")
    
    refined_model: Dict[str, Any] = Field(
        ...,
        alias="refinedModel",
        description="The refined domain model"
    )
    changes_applied: List[Dict[str, Any]] = Field(
        default_factory=list,
        alias="changesApplied",
        description="List of changes applied to the original model"
    )
    
    metadata: Optional[Dict[str, Any]] = Field(None)

    class Config:
        populate_by_name = True

    def to_artifact(self) -> Artifact:
        """Convert to standard A2A Artifact."""
        return Artifact(
            artifact_id=self.artifact_id,
            name=self.name,
            description=self.description,
            parts=[Part.from_data({
                "refinedModel": self.refined_model,
                "changesApplied": self.changes_applied
            })],
            metadata=self.metadata
        )
