"""
A2A Protocol - Task Model

Task is the core unit of action for A2A. It has a current status and when results 
are created for the task they are stored in artifacts. If there are multiple turns 
for a task, these are stored in history.

Based on A2A Protocol Specification v0.3
"""

from enum import Enum
from typing import Optional, List, Dict, Any
from datetime import datetime
from pydantic import BaseModel, Field
import uuid


class TaskState(str, Enum):
    """
    Defines the possible lifecycle states of a Task.
    """
    UNSPECIFIED = "unspecified"
    SUBMITTED = "submitted"      # Task is created, acknowledged
    WORKING = "working"          # Task is actively being processed
    COMPLETED = "completed"      # Task finished successfully (terminal)
    FAILED = "failed"            # Task done but failed (terminal)
    CANCELLED = "cancelled"      # Task was cancelled (terminal)
    INPUT_REQUIRED = "input-required"  # Task needs more info (interrupted)
    REJECTED = "rejected"        # Agent decided not to perform task (terminal)
    AUTH_REQUIRED = "auth-required"    # Authentication needed


class TaskStatus(BaseModel):
    """
    A container for the status of a task.
    """
    state: TaskState = Field(
        ...,
        description="The current state of this task"
    )
    message: Optional["Message"] = Field(
        None,
        description="A message associated with the status"
    )
    timestamp: Optional[datetime] = Field(
        default_factory=datetime.utcnow,
        description="ISO 8601 Timestamp when the status was recorded"
    )

    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat() + "Z"
        }


class Task(BaseModel):
    """
    Task is the core unit of action for A2A.
    
    It has a current status and when results are created for the task 
    they are stored in artifacts. If there are multiple turns for a task, 
    these are stored in history.
    """
    id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique identifier (UUID) for the task, generated by the server"
    )
    context_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        alias="contextId",
        description="Unique identifier for the contextual collection of interactions"
    )
    status: TaskStatus = Field(
        ...,
        description="The current status of the Task, including state and message"
    )
    artifacts: Optional[List["Artifact"]] = Field(
        None,
        description="A set of output artifacts for the Task"
    )
    history: Optional[List["Message"]] = Field(
        None,
        description="The history of interactions from the task"
    )
    metadata: Optional[Dict[str, Any]] = Field(
        None,
        description="A key/value object to store custom metadata about the task"
    )

    class Config:
        populate_by_name = True
        json_encoders = {
            datetime: lambda v: v.isoformat() + "Z"
        }

    @classmethod
    def create_new(
        cls,
        context_id: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None
    ) -> "Task":
        """
        Factory method to create a new Task in SUBMITTED state.
        """
        return cls(
            id=str(uuid.uuid4()),
            context_id=context_id or str(uuid.uuid4()),
            status=TaskStatus(state=TaskState.SUBMITTED),
            artifacts=[],
            history=[],
            metadata=metadata or {}
        )

    def transition_to(self, new_state: TaskState, message: Optional["Message"] = None) -> None:
        """
        Transition the task to a new state.
        
        Args:
            new_state: The new TaskState
            message: Optional message associated with the transition
        """
        # Validate state transitions
        terminal_states = {TaskState.COMPLETED, TaskState.FAILED, TaskState.CANCELLED, TaskState.REJECTED}
        
        if self.status.state in terminal_states:
            raise ValueError(f"Cannot transition from terminal state {self.status.state}")
        
        self.status = TaskStatus(
            state=new_state,
            message=message,
            timestamp=datetime.utcnow()
        )

    def add_artifact(self, artifact: "Artifact") -> None:
        """Add an artifact to the task."""
        if self.artifacts is None:
            self.artifacts = []
        self.artifacts.append(artifact)

    def add_to_history(self, message: "Message") -> None:
        """Add a message to the task history."""
        if self.history is None:
            self.history = []
        self.history.append(message)

    def is_terminal(self) -> bool:
        """Check if the task is in a terminal state."""
        terminal_states = {TaskState.COMPLETED, TaskState.FAILED, TaskState.CANCELLED, TaskState.REJECTED}
        return self.status.state in terminal_states

    def is_working(self) -> bool:
        """Check if the task is actively being processed."""
        return self.status.state == TaskState.WORKING


class TaskStatusUpdateEvent(BaseModel):
    """
    An event sent by the agent to notify the client of a change in a task's status.
    Used for streaming and push notifications.
    """
    task_id: str = Field(..., alias="taskId", description="The id of the task that changed")
    context_id: str = Field(..., alias="contextId", description="The id of the context")
    status: TaskStatus = Field(..., description="The new status of the task")
    final: bool = Field(..., description="If true, this is the final event in the stream")
    metadata: Optional[Dict[str, Any]] = Field(None, description="Optional metadata")

    class Config:
        populate_by_name = True


class TaskArtifactUpdateEvent(BaseModel):
    """
    TaskArtifactUpdateEvent represents a task delta where an artifact has been generated.
    Used for streaming artifact updates.
    """
    task_id: str = Field(..., alias="taskId", description="The id of the task")
    context_id: str = Field(..., alias="contextId", description="The id of the context")
    artifact: "Artifact" = Field(..., description="The artifact that was generated or updated")
    append: Optional[bool] = Field(None, description="If true, append to previous artifact with same ID")
    last_chunk: Optional[bool] = Field(None, alias="lastChunk", description="If true, final chunk")
    metadata: Optional[Dict[str, Any]] = Field(None, description="Optional metadata")

    class Config:
        populate_by_name = True


# Forward references for type hints
from a2a.models.message import Message
from a2a.models.artifact import Artifact

# Update forward references
TaskStatus.model_rebuild()
Task.model_rebuild()
TaskStatusUpdateEvent.model_rebuild()
TaskArtifactUpdateEvent.model_rebuild()
